# Generated by Django 4.2.30 on 2026-05-15 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_hi', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_hi', models.TextField(blank=True)),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_percentage', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('skills_required', models.JSONField(default=list)),
                ('market_demand', models.IntegerField(default=50)),
                ('risk_level', models.IntegerField(default=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'business_ideas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_hi', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('description_hi', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='BusinessRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadmap_data', models.JSONField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='businesses.businessidea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_roadmaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='businessidea',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='businesses.category'),
        ),
        migrations.CreateModel(
            name='SavedBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='businesses.businessidea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_businesses',
                'unique_together': {('user', 'business')},
            },
        ),
    ]
