# Generated by Django 4.2.30 on 2026-05-24 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessroadmap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_roadmaps', to=settings.AUTH_USER_MODEL),
        ),
    ]
